export default {
	EMAIL_CHANGED: 'EMAIL_CHANGED',
	PASS_CHANGED: 'PASS_CHANGED',

	REQ_AUTH: 'REQ_AUTH',
	AUTH_SUCCESS: 'AUTH_SUCCESS',
	AUTH_ERROR: 'AUTH_ERROR',

	SET_USER: 'SET_USER',

	CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
	UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
	FETCH_EMPLOYEES: 'FETCH_EMPLOYEES',
	FETCH_EMPLOYEES_SUCCESS: 'FETCH_EMPLOYEES_SUCCESS',

	EMPLOYEES_FAILURE: 'EMPLOYEES_FAILURE',
};
